# ! Change this to be your URL and Name ! 
baseurl      = "YourSiteURL.GoesHere"
title        = "Your Page title goes here, for example use your Name"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

# Google Analytics - ! Change this to be your ID or remove ! 
#  googleAnalytics = 'If you have a Tag ID, place it here and uncomment this line'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home ! Change this if you wish ! 
  homeSubtitle = "This is a the homeSubtitle that is placed on the page, something like 'where to find me'"


  # Metadata mostly used in document's head ! Change this if you wish !
  description = "My Social Media Links"
  keywords = "homepage, blog, social"
  images = [""]

[author]
# ! Change this !
  name = "Put your Name here"

 # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
#    trademark = true
#    rss = true
#    copyright = true
#    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"https://developers.cloudflare.com/pages/\">Cloudflare Pages</a>",
    ] 


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    # ! Change this if you wish !
    title = "This is the title field, that is placed on the page, something like 'Connect with me'"
    subtitle = "My links"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params.logo]
    # ! Change this !
      logoText = "This is the logoText field, that is placed on the page, something like 'Your Name'"
      logoHomeLink = "/"

  # ! Change these !
  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "yourtwitterurl.com"

  [[params.social]]
    name = "email"
    url  = "mailto:youremail@dot.com"

  [[params.social]]
    name = "github"
    url  = "yourGithubURL.com or remove block"

  [[params.social]]
    name = "linkedin"
    url  = "your LinkedinURL.com or remove"
